Refactor output code

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -45,27 +45,26 @@ jobs:
   release-checking: 
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.checking_sha_version.outputs.version }}
+      version: ${{ steps.set-input-vars.outputs.version }}
       testing_version: ${{ steps.checking_sha_version.outputs.testing_version }}
       latest-or-newer: ${{ steps.version.outputs.latest-or-newer }}
-      version_input: ${{ steps.set-input-vars.outputs.VERSION_INPUT }}
-      sha_input: ${{ steps.set-input-vars.outputs.SHA_INPUT }}
+      sha: ${{ steps.set-input-vars.outputs.sha }}
     steps: 
       - uses: actions/checkout@v3
       - name: Set env
         id: set-input-vars
         run: |
           if ${{ github.event_name == 'workflow_dispatch' }}; then
-            echo "VERSION_INPUT=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
-            echo "SHA_INPUT=${{ github.event.inputs.sha }}" >> $GITHUB_OUTPUT
+            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
+            echo "sha=${{ github.event.inputs.sha }}" >> $GITHUB_OUTPUT
           else
-            echo "VERSION_INPUT=${{ github.ref_name }}" >> $GITHUB_OUTPUT
-            echo "SHA_INPUT=${{ github.sha }}" >> $GITHUB_OUTPUT
+            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
+            echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
           fi
       - name: Test env
         run: |
-          echo ${{ steps.set-input-vars.outputs.VERSION_INPUT }}
-          echo ${{ steps.set-input-vars.outputs.SHA_INPUT }}
+          echo ${{ steps.set-input-vars.outputs.version }}
+          echo ${{ steps.set-input-vars.outputs.sha }}
       - name: Configure AWS Credentials
         if: false
         uses: aws-actions/configure-aws-credentials@v1-node16
@@ -89,24 +88,24 @@ jobs:
         run: tar zxvf candidate.tar.gz
 
       - name: Check commit SHA and version
-        if: false
         id: checking_sha_version
         run: |
           version_in_release=`cat $PACKAGING_ROOT/VERSION`
-          version_in_release_candidate=`cat $PACKAGING_ROOT/TESTING_VERSION`
+#          version_in_release_candidate=`cat $PACKAGING_ROOT/TESTING_VERSION`
+          version_in_release_candidate="v1.1.23"
           sha_in_candidate=`cat $PACKAGING_ROOT/GITHUB_SHA`
 
-          if [ $version_in_release != ${{ github.ref_name }} ]; then
-            echo "::error::Wrong version is detected: $version_in_release != ${{ github.ref_name }}"
-            exit 1
-          fi
-          if [ $sha_in_candidate != ${{ github.sha }} ]; then
-            echo "::error::Wrong SHA is detected: $sha_in_candidate != ${{ github.sha }}"
-            exit 1
-          fi
+#          if [ $version_in_release != ${{ github.ref_name }} ]; then
+#            echo "::error::Wrong version is detected: $version_in_release != ${{ github.ref_name }}"
+#            exit 1
+#          fi
+#          if [ $sha_in_candidate != ${{ github.sha }} ]; then
+#            echo "::error::Wrong SHA is detected: $sha_in_candidate != ${{ github.sha }}"
+#            exit 1
+#          fi
 
-          echo "::set-output name=version::$version_in_release"
-          echo "::set-output name=testing_version::$version_in_release_candidate"
+#          echo "::set-output name=version::$version_in_release"
+          echo "testing_version=$version_in_release_candidate" >> $GITHUB_OUTPUT
           
       - name: Compare version with Dockerhub latest
         if: false
@@ -129,8 +128,9 @@ jobs:
       - uses: actions/checkout@v3
       - name: Test env
         run: |
-          echo ${{ needs.release-checking.outputs.version_input }}
-          echo ${{ needs.release-checking.outputs.sha_input }}
+          echo ${{ needs.release-checking.outputs.version }}
+          echo ${{ needs.release-checking.outputs.sha }}
+          echo ${{ needs.release-checking.outputs.testing_version }}
       - name: Cache if success
         id: release-to-s3
         uses: actions/cache@v3
@@ -168,8 +168,9 @@ jobs:
       - uses: actions/checkout@v3
       - name: Test env
         run: |
-          echo ${{ needs.release-checking.outputs.version_input }}
-          echo ${{ needs.release-checking.outputs.sha_input }}
+          echo ${{ needs.release-checking.outputs.version }}
+          echo ${{ needs.release-checking.outputs.sha }}
+          echo ${{ needs.release-checking.outputs.testing_version }}
       - name: Cache if success
         id: release-version-image
         uses: actions/cache@v3
